config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:index, :new, :create, :destroy]
end

app/models/note.rb
class Note < ApplicationRecord

  validates :comment, :user_id, :track_id, presence: true

  belongs_to :user,
    class_name: :User,
    foreign_key: :user_id,
    primary_key: :id,
    optional: true

  belongs_to :track,
    class_name: :Track,
    foreign_key: :track_id,
    primary_key: :id,
    optional: true
  
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    # render "form"
  end

  def create
    params[:note][:user_id] = current_user.id
    @note = Note.new(note_params)
    if @note.save
      redirect_to track_url(@note.track)
    else
      flash.now[:errors] = @note.errors.full_messages
      redirect_to track_url(@note.track)
    end
  end

  def destroy
    @note = Note.find_by(id: params[:id])
    if current_user.id != @note.user_id
      render status: :forbidden, text: "You can't detroy this comment"
    else
      @note.destroy
      redirect_to track_url(@note.track)
    end
  end

  private
  def note_params
    params.require("note").permit(:comment, :user_id, :track_id)
  end
end

app/views/notes/_form.html.erb
<h2>New Note</h2>
<form action="<%= notes_url %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="note[track_id]" value="<%=track.id %>">

  <label for="comment">Content</label>
  <textarea id="comment" name="note[comment]" rows="8" cols="80">
  </textarea>
  <br>

  <input type="submit" value="Submit">

</form>

app/views/notes/_note.html.erb
<h2>Notes</h2>

<p>
  <% notes.each do |note|%>
    <%= note.comment %>
    <br>
    Authored by: <%= note.user.email %>
    <br>
    <% if current_user.id == note.user_id %>
      <form action="<%= note_url(note) %>" method="post">
        <%= auth_token %>
        <input type="hidden" name="_method" value="DELETE">

        <input type="submit" value="Delete">

      </form>
    <% end %>
    <br>
  <% end %>
</p>