config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:index, :new, :create, :destroy]
end

app/models/album.rb
class Album < ApplicationRecord
  KIND = %w(studio live)

  validates :title, :year, :band_id, presence: true
  validates :kind, inclusion: { in: KIND }

  belongs_to :band,
    class_name: :Band,
    foreign_key: :band_id,
    primary_key: :id,
    optional: true

  has_many :tracks,
    class_name: :Track,
    foreign_key: :album_id,
    primary_key: :id,
    dependent: :destroy

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :logged_in_user!

  def show
    #/albums/:id
    @album = Album.find_by(id: params[:id])
    if @album.nil?
      render json: "Couldn\'t find"
    else
      render :show
    end
  end

  def new
    #/bands/:band_id/albums/new
    @band = Band.find_by(id: params[:band_id])
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    # POST:  /albums
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      # render json: flash.now[:errors]
      @band = @album.band
      @bands = Band.all
      render :new
      # redirect_to new_band_album_url(@album.band)
      # render json: "not saved"
    end
  end

  def edit
    # /albums/:id/edit
    @album = find_by(id: params[:id])
    @bands = Band.all
    render :edit
  end

  def update
    # PATCH: /albums/:id
    @album = find_by(id: params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      redirect_to edit_album_url(@album)
    end
  end

  def destroy
    # DELETE: /albums/:id
    @album = Album.find_by(id: params[:id])
    if @album.destroy
      redirect_to band_url(@album.band)
    else
      redner json: "Couldn\'t destroy"
    end
  end

  private
  def album_params
    params.require("album").permit(:title, :year, :band_id, :kind)
  end

end

app/views/albums/_form.html.erb
<% action = album.persisted? ? album_url(album) : albums_url %>
<% method = album.persisted? ? "PATCH" : "POST" %>
<% title = album.persisted? ? album.title : "" %>
<% yr = album.persisted? ? album.year : "" %>
<% button = album.persisted? ? "Update" : "Add" %>

<form action="<%= action %>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="title">Title</label>
  <input id="title" type="text" name="album[title]" value="<%=title%>">
  <br>

  <label for="year">Year</label>
  <input id="year" type="text" name="album[year]" value="<%= yr%>">
  <br>

  <label for="band">Band</label>
  <select id="band" name="album[band_id]">

    <% bands.each do |band| %>
      <% selected = "selected" if band.id.to_s == params[:band_id] %>

      <option value="<%= band.id%>"
        <%= selected %> ><%=band.name %></option>
    <% end %>
  </select>
  <br>

  <label>
    <% Album::KIND.each do |kind| %>
      <input type="radio"
       <%= "checked" if album.kind == kind %>
       name="album[kind]"
       value="<%=kind%>">
      <%= kind.upcase %>
    <% end %>
  </label>
  <br>

  <input type="submit" value="<%=button %>">

</form>

app/views/albums/edit.html.erb
<h1>Edit <%= @album.title %></h1>

<%= render 'layouts/errors' %>
<%= render "form", album: @album, bands: @bands %>

app/views/albums/new.html.erb
<h1>New <%= @band.name %> Album! </h1>

<%= render 'layouts/errors' %>
<%= render "form", album: @album, bands: @bands %>

app/views/albums/show.html.erb
<h1> <%= @album.title %></h1>

<h2>Tracks</h2>
  <% @album.tracks.each do |track| %>
    <a href=<%= track_url(track)%>> <%= track.title %> </a>
  <% end %>

<h3>Links</h3>
<a href="<%= new_album_track_url(@album) %>">New Track</a>

<a href="<%= edit_album_url(@album) %>">Edit Album</a>
<br>
<form action="<%= album_url(@album)%>" method="post">
  <%= auth_token %>
  <input type="hidden" name="_method" value="DELETE">
  <input type="submit" value="Delete Album">
</form>
<br>
<a href="<%= band_url(@album.band_id) %>">Back to <%= @album.band.name %></a>