config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, except: [:index, :new] do
    resources :tracks, only: :new
  end

  resources :tracks, except: [:index, :new]

  resources :notes, only: [:index, :new, :create, :destroy]
end

app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true

  has_many :albums,
    class_name: :Album,
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :logged_in_user!

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find_by(id: params[:id])
    if @band.nil?
      redirect_to bands_url
    else
      render :show
    end
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      redirect_to new_band_url
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    if @band.nil?
      render json: "Not such a band found"
    else
      render :edit
    end
  end

  def update
    @band = Band.find_by(id: params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    if @band.destroy
      redirect_to band_url
    else
      render json: "Couldn\'t destroy"
    end
  end

  private
  def band_params
    params.require("band").permit(:name)
  end

end

app/views/bands/_form.html.erb
<% action = band.persisted? ? band_url(band) : bands_url %>
<% method = band.persisted? ? "patch" : "post" %>
<% val = band.persisted? ? band.name : "" %>
<% button = band.persisted? ? "Update" : "Create" %>

<form action="<%= action %>" method="post">
  <%= auth_token %>

  <input type="hidden" name="_method" value="<%= method %>">

  <label for="name">Name</label>
  <input id="name" type="text" name="band[name]" value="<%= val %>">
  <br>

  <input type="submit" value="<%= button %>">

</form>

app/views/bands/edit.html.erb
<h1>Edit <%= @band.name %></h1>

<%= render 'layouts/errors' %>
<%= render "form", band: @band %>

app/views/bands/index.html.erb
<a
  style="display: flex; flex-direction: column; align-items: flex-end"
   href="<%=new_band_url  %>">New Band</a>
<h1>All Bands</h1>

<% @bands.each do |band| %>

  <a href="<%= band_url(band) %>">
    <%= band.name %>
  </a>


<% end %>
<br>

app/views/bands/new.html.erb
<h1>Create a band</h1>

<%= render 'layouts/errors' %>
<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1> <%= @band.name %> </h1>

<p>
  This band has been creted at <%= @band.created_at %>
</p>
<br>

<h2>Albums</h2>
<% @band.albums.each do |album| %>

  <a href="<%= album_url(album)%>"><%=album.title %></a>

<% end %>

<h3>Links</h3>
<div>
  <a href="<%= edit_band_url(@band) %>">Edit Band</a>
  <a href="<%= bands_url%>"> All bands</a>
  <form class="default_form" action="<%=band_url(@band)  %>" method="post">
    <%= auth_token %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete Band">
  </form>
  <a href="<%= new_band_album_url(@band) %>">New Album</a>
</div>